/** Declaration file generated by dts-gen */

export class elementResizeEvent {
    constructor(window: any);
    addResizeListener(element: any, fn: any): void;
    removeResizeListener(element: any, fn: any): void;
}
